from setuptools import setup

setup(
    name='PandoraBot',
    version='',
    packages=['venv.lib.python3.5.distutils', 'venv.lib.python3.5.encodings', 'venv.lib.python3.5.importlib',
              'venv.lib.python3.5.collections', 'venv.lib.python3.5.site-packages.pip',
              'venv.lib.python3.5.site-packages.pip.req', 'venv.lib.python3.5.site-packages.pip.vcs',
              'venv.lib.python3.5.site-packages.pip.utils', 'venv.lib.python3.5.site-packages.pip.compat',
              'venv.lib.python3.5.site-packages.pip.models', 'venv.lib.python3.5.site-packages.pip._vendor',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip.commands', 'venv.lib.python3.5.site-packages.pip.operations',
              'venv.lib.python3.5.site-packages.click', 'venv.lib.python3.5.site-packages.flask',
              'venv.lib.python3.5.site-packages.flask.ext', 'venv.lib.python3.5.site-packages.wheel',
              'venv.lib.python3.5.site-packages.wheel.tool', 'venv.lib.python3.5.site-packages.wheel.signatures',
              'venv.lib.python3.5.site-packages.jinja2', 'venv.lib.python3.5.site-packages.werkzeug',
              'venv.lib.python3.5.site-packages.werkzeug.debug', 'venv.lib.python3.5.site-packages.werkzeug.contrib',
              'venv.lib.python3.5.site-packages.markupsafe', 'venv.lib.python3.5.site-packages.setuptools',
              'venv.lib.python3.5.site-packages.setuptools.extern',
              'venv.lib.python3.5.site-packages.setuptools.command', 'venv.lib.python3.5.site-packages.pkg_resources',
              'venv.lib.python3.5.site-packages.pkg_resources.extern',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor.packaging'],
    url='https://jacksonhu.com',
    license='CC-BY-SA 4.0',
    author='"Jackson" Ming Hu',
    author_email='huming2207@gmail.com',
    description=''
)
